services:
    mongodb:
        image: mongo:latest
        container_name: mongodb_nyt
        volumes:
          - ./docker_mongo:/data/db
          - ./data:/data/db/data
          - .env:/data/db/.env
          - ./mongodb/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh:ro

        ports:
          - 27017:27017
        env_file:
          - .env
        environment:
          - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
          - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
          - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
        networks:
          - mongo-compose-network

    mongoexpress:
        container_name: mongo-express
        image: mongo-express:1.0.0-20
        restart: on-failure
        env_file:
          - .env
        depends_on:
          - mongodb
        networks:
          - mongo-compose-network
        environment:
          - ME_CONFIG_MONGODB_SERVER=mongodb
          - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
          - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
          - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
          - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
          - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
        ports:
          - '8081:8081'
        volumes:
          - ./docker_mongo:/data/db

    app:
      container_name: app
      restart: on-failure
      build:
        context: ./app
        dockerfile: Dockerfile
      depends_on:
        - mongodb
      networks:
        - mongo-compose-network

    polarity:
      container_name: polarity_trainer
      build:
        context: ./ml/polarity
        dockerfile: Dockerfile
      depends_on:
        - mongodb
      networks:
        - mongo-compose-network
      volumes:
        - ./ml/models:/models

    prediction:
      container_name: predict
      build:
        context: ./ml/predict
        dockerfile: Dockerfile
      networks:
        - mongo-compose-network
      ports:
        - '8003:8003'
      volumes:
        - ./ml/models:/models

networks:
  mongo-compose-network:
