services:
    mongodb:
        image: mongo:latest
        container_name: mongodb_nyt
        volumes:
          - ./data_mongo:/data/db
          - .env:/data/db/.env
          - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh:ro

        ports:
          - 27017:27017
        env_file:
          - path: .env
        environment:
          - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
          - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
          - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
        networks: 
          - mongo-compose-network

    mongoexpress:
        container_name: mongo-express
        image: mongo-express:1.0.0-20
        restart: on-failure
        env_file:
          - path: .env
        depends_on:
          - mongodb
        networks: 
          - mongo-compose-network
        environment:
          - ME_CONFIG_MONGODB_SERVER=mongodb
          - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
          - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
          - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
          - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
          - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
        ports:
          - '8081:8081'
        volumes: 
          - ./data_mongo:/data/db


networks:
  mongo-compose-network: